version: "3.0"
services:
  mongoDB:
    image: mongo:latest
    container_name: mongoDB-shop
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongoDB:/data/db
volumes:
  mongoDB: {}
